#!/usr/bin/env zsh

# clone
#   SSH Git clone utility.
#
# Note:
#   Expects $GIT_USERNAME to be set.

if [[ -z "${GIT_USERNAME}" ]]; then
    echo "error: \$GIT_USERNAME is not set." >&2
    exit 1
fi

usage() {
    echo "Usage: clone <repo> [directory]"
    echo ""
    echo "Arguments:"
    echo "  repo         Repository name to clone"
    echo "  directory    Optional target directory"
    echo ""
    echo "Note: Requires \$GIT_USERNAME to be set."
}

case $# in
    1)
        git clone git@github.com:${GIT_USERNAME}/$1
    ;;
    2)
        git clone git@github.com:${GIT_USERNAME}/$1 $2
    ;;
    *) 
        usage
    ;;
esac
