#!/usr/bin/env bash

# flip
#   Switch between light and dark mode themes in Ghostty and Helix. 
#
# Note:
#   The following environment variables must be set:
#     GHOSTTY_CONFIG - Path to ghostty config directory.
#     GHOSTTY_DARK   - Name of ghostty dark theme.
#     GHOSTTY_LIGHT  - Name OF ghostty light theme.
#     HELIX_CONFIG   - Path to helix config directory.
#     HELIX_DARK     - Name of helix dark theme.
#     HELIX_LIGHT    - Name of helix light theme.

SETTING="theme = "

# Print usage.
usage() {
  echo "Switch between light and dark mode in Ghostty and Helix."
  echo
  echo "Usage: flip [dark|light]"
  exit 1
}

# Replace first line in config file.
replace_first_line() {
    local file="$1"
    local newline="$2"
    local tmpfile
    tmpfile=$(mktemp)

    echo "$newline" > "$tmpfile"
    tail -n +2 "$file" >> "$tmpfile"

    # Overwrite target contents, keep symlink intact
    cat "$tmpfile" > "$file"
    rm "$tmpfile"
}

MODE="$1"
case "$MODE" in
    dark)
        GHOSTTY_THEME="$GHOSTTY_DARK"
        HELIX_THEME="$HELIX_DARK"
        ;;
    light)
        GHOSTTY_THEME="$GHOSTTY_LIGHT"
        HELIX_THEME="$HELIX_LIGHT"
        ;;
    *)
        usage
        ;;
esac

# Change themes.
replace_first_line "$GHOSTTY_CONFIG" "$SETTING$GHOSTTY_THEME"
replace_first_line "$HELIX_CONFIG"  "$SETTING\"$HELIX_THEME\""

# Launch ghostty (detached from current shell).
nohup ghostty >/dev/null 2>&1 &
disown

exec exit
